# Conexao com o Banco de Dados Aiven na Nuvem
spring.datasource.url=jdbc:mysql://spotmusic-db-projetospotmusic.f.aivencloud.com:20209/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# Mantem a criacao automatica das tabelas (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true